### ISSUE TITLE
AsyncRequestTimeoutException 관련 논의

### ISSUE THREAD

**Issue by Chaeyounglim** [sangbu3jo/Elephant#35]
### 성능 최적화를 위한 트러블 슈팅 이슈

AsyncRequestTimeoutException과 관련된 동기/비동기 이슈 고민해봐야 합니다.
각자 더 찾아보고 이야기하는게 좋을 것 같으니 중간 발표 끝나고 논의.

- [ ] EmailService에 @Async 여부 필수/선택인지 테스트해보기
- [ ] 서버측의 요청 수행 시간이 길어짐에 따른 문제 고민

**Comment by iamzin** [comment]
Async를 쓰지 않으려는 이유는 뭘까요?

**Comment by Chaeyounglim** [comment]
발표가 끝나고 논의하여 내용을 추가하겠습니다.
