### ISSUE TITLE
[Common] 주석 정리

### ISSUE THREAD

**Issue by iamzin** [sangbu3jo/Elephant#44]
전체적으로 코드 정리가 필요해보입니다.
각자 완료 후에 아래 체크리스트 표시해서 코멘트로 달아보세요. :)

- [ ] 안쓰는 주석처리된것 삭제
- [ ] 설명하는 주석 java docs로 변경

**Comment by gunwooknam2023** [comment]
확인부탁드립니다 감사합니다 튜터님

**Comment by gunwooknam2023** [comment]
#52

**Comment by Chaeyounglim** [comment]
안쓰는 주석 처리 된 것 삭제하였습니다.
설명하는 주석 java docs를 활용하여 명시해두었습니다.

부족한 부분 확인해주시면 감사하겠습니다.

**Comment by iamzin** [comment]
@Chaeyounglim 님, 깔끔하게 잘 정리해주셨네요!
return 값이 있는 것들은 return 타입 명시와 also see 라는 것도 활용해보면 더욱 좋겠습니다. :)

**Comment by azuressu** [comment]
안쓰는 주석은 삭제하였습니다 !
설명하는 주석은 Java Docs를 사용해 적어보았습니다 !
미흡한 부분이 있다면 알려주시면 감사하겠습니다 :D

**Comment by HyunJooong** [comment]
불필요한 주석과 클래스 파일 정리 했습니다 확인 부탁 드립니다
