### ISSUE TITLE
[Common] 관심사 분리

### ISSUE THREAD

**Issue by iamzin** [sangbu3jo/Elephant#45]
현재 구현하신 레이어들(Controller, Service, Repository)의 관심사를 적절히 분리했는지 점검합니다.
`관심사 분리 SoC; Separation of Concerns`에 대해 찾아보고 정리한 내용을 코멘트로 남겨주세요.

**Comment by azuressu** [comment]
**관심사 분리 (SoC: Separation of Concerns)**
시스템 요소가 단일 목적이고 베타성을 가져야 한다는 것입니다.
어떤 요소도 다른 요소와 책임을 공유하면 안되고, 그 요소가 관계 없는 책임을 포함할 수 없다는 것입니다.

관심사 분리는 경계를 세우는 것으로 완성되는데,
경계는 주어진 책임 세트를 설명하는 논리적 혹은 물리적인 제한입니다.

관심사 분리는 질서에 관한 것이라고 할 수 있습니다.
종합적인 목표는 각 파트가 의미있고 직관적인 규칙을 수행하지만,
변화에 적응하는 능력을 극대화하는 잘 조직된 시스템을 설립하는 것입니다. 

**관심사 분리 방법**
1) 수평적 분리 (Horizontal Separation)
애플리케이션 내의 동일한 규칙을 수행하는 기능의 논리적 레이어 단위로 앱을 분리하는 프로세스입니다.

2) 수직적 분리 (Vertical Separation)
애플리케이션을 (혹은 애플리케이션 내의 동일한 피처나 서브 시스템과 관련된) 기능 모듈로 분리하는 프로세스입니다.

3) 횡단 관심사 분리 (Aspect Separation)
애플리케이션의 횡단 관심사 (cross-cuttion concerns)를 분리하는 프로세스입니다.
