### ISSUE TITLE
[Convention] Pull Request Template 구성

### ISSUE THREAD

**Issue by iamzin** [sangbu3jo/Elephant#47]
Pull Request Template 구성해 봅시다.

**Comment by azuressu** [comment]
PR Template 구성하여 추가했습니다 !
확인해주시면 감사하겠습니다 :D

**Comment by iamzin** [comment]
템플릿은 적용이 됐는데, 내용이 부실하군요!😭

제목에는 어떤 목적으로 생성된 pr인지 명확히 구분할 수 있어야 합니다.
또한 템플릿을 쓰는 이유는 다른 사람이 해당 description만 보고도 어떤 작업을 수행했는지 알기 위함입니다.
따라서 어떤 코드를 왜 고쳤는지, 영향도 있는 다른 부분은 어떤 것이 있는지 등 상세하게 작성하시면 좋을 것 같습니다.

**Comment by Chaeyounglim** [comment]
@iamzin 
튜터님 혹시 #71 PR 내용처럼 작성하는건 괜찮을까요?
